version: '3'

services:

  master:
    image: local/ansible-master
    command: tail -f /dev/null
    working_dir: /ansible
    volumes:
      - ./ansible:/ansible

  slave1: &slave
    command: /usr/sbin/sshd -D
    image: local/ansible-slave

  slave2:
    <<: *slave

  slave3:
    <<: *slave

  slave4:
    <<: *slave
